# Generated by Django 2.0.13 on 2019-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
